# sql_pipeline.yaml
# ─────────────────────────────────────────────────────────────────────
# Pulls todos from JSONPlaceholder, validates with Pydantic, cleans,
# and persists to a local SQLite database.
# ─────────────────────────────────────────────────────────────────────

version: "1.0"

pipeline:
  name: "jsonplaceholder_to_sqlite"
  description: "Pull todos from JSONPlaceholder and save to SQLite."

  # ── Extract ────────────────────────────────────────────────────────
  extract:
    source: "rest_api"
    config_file: "configs/sources/jsonplaceholder.yaml"

  # ── Transform (chain executed top-to-bottom) ───────────────────────
  transform:
    - name: "pydantic_validation"
      config_file: "configs/transforms/pydantic_validation.yaml"
    - name: "data_cleaning"
      config_file: "configs/transforms/data_cleaning.yaml"

  # ── Load ───────────────────────────────────────────────────────────
  load:
    destination: "sql_database"
    config_file: "configs/loaders/sql_database.yaml"

# ── Global settings ──────────────────────────────────────────────────
settings:
  log_level: "INFO"
  retry:
    max_attempts: 3
    backoff_seconds: 2
  on_failure: "abort"
